import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../../lib/api.js'
import { useApp } from '../../lib/app-context.jsx'
import { PageTitle } from '../../components/layout.jsx'
import { Card, Badge, Button, Spinner, ErrorState, EmptyState, Field, inputStyle } from '../../components/ui.jsx'

export default function LearnerQuizzes () {
  const { t } = useApp()
  const [quizzes, setQuizzes] = useState(null)
  const [err, setErr] = useState(null)
  const [genOpen, setGenOpen] = useState(false)
  const [topic, setTopic] = useState('Sampling')
  const [text, setText] = useState('')
  const [useSample, setUseSample] = useState(true)
  const [busy, setBusy] = useState(false)
  const [genNote, setGenNote] = useState(null)

  async function load () {
    try { setQuizzes((await api.get('/api/quizzes')).quizzes) } catch (e) { setErr(e) }
  }
  useEffect(() => { load() }, [])

  async function generate () {
    setBusy(true); setErr(null); setGenNote(null)
    try {
      const d = await api.post('/api/quizzes/generate', { topic, text, use_sample: useSample })
      setGenNote(d)
      await load()
    } catch (e) { setErr(e) } finally { setBusy(false) }
  }

  if (err && !quizzes) return <ErrorState message={err.message} onRetry={load} />
  if (!quizzes) return <Spinner />

  return (
    <>
      <PageTitle
        title={t('nav.quizzes')}
        subtitle="Published quizzes are trainer-approved. Generated quizzes wait in review before learners can attempt them."
        actions={<Button onClick={() => setGenOpen(o => !o)}>{genOpen ? 'Close generator' : t('quiz.gen')}</Button>}
      />
      {err && <div style={{ marginBottom: 14 }}><ErrorState message={err.message} onRetry={() => setErr(null)} /></div>}

      {genOpen && (
        <Card style={{ marginBottom: 20, borderTop: '4px solid var(--teal-600)' }}>
          <h3 style={{ fontSize: 16 }}>Generate a grounded quiz</h3>
          <p style={{ fontSize: 13.2, color: 'var(--ink-500)', marginTop: 2 }}>
            Upload text from a learning document (or use the sample). Generated questions carry source references.
            Without AI credentials the generator uses a rules-based fallback and says so — nothing is presented as live AI.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '0 18px' }}>
            <Field label="Topic (matches a competency name)">
              <input style={inputStyle} value={topic} onChange={e => setTopic(e.target.value)} placeholder="e.g. Sampling" />
            </Field>
            <Field label="Source">
              <label style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 14, paddingTop: 8 }}>
                <input type="checkbox" checked={useSample} onChange={e => setUseSample(e.target.checked)} />
                Use built-in sample document
              </label>
            </Field>
          </div>
          {!useSample && (
            <Field label="Document text (min 40 characters)">
              <textarea rows={6} style={inputStyle} value={text} onChange={e => setText(e.target.value)} placeholder="Paste text extracted from a .txt / .md / .csv learning document…" />
            </Field>
          )}
          <Button onClick={generate} loading={busy} disabled={!useSample && text.trim().length < 40}>
            {t('action.generate')} {useSample ? '(sample document)' : ''}
          </Button>
          {genNote && (
            <div style={{
              marginTop: 14, borderRadius: 10, padding: '12px 14px',
              background: genNote.mode === 'ai' ? 'var(--success-bg)' : 'var(--warn-bg)',
              color: genNote.mode === 'ai' ? 'var(--success)' : 'var(--warn)',
              fontSize: 13.5
            }}>
              <strong>{genNote.mode === 'ai' ? `Generated by live AI (${genNote.model})` : 'Fallback generator (not live AI)'}</strong>
              <div>{genNote.note}</div>
              <div style={{ marginTop: 6 }}>
                Quiz “{topic} — generated quiz” created with {genNote.question_count} questions, status <strong>in review</strong>.
                A trainer must approve it before it appears here.
              </div>
            </div>
          )}
        </Card>
      )}

      {quizzes.length === 0
        ? <EmptyState title="No published quizzes yet" hint="Generate one above — it will appear once a trainer approves it." />
        : (
          <div style={{ display: 'grid', gap: 12 }}>
            {quizzes.map(q => (
              <Card key={q.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
                <div>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                    <h3 style={{ fontSize: 15.5, margin: 0 }}>{q.title}</h3>
                    {q.competency_name && <Badge kind="teal">{q.competency_name}</Badge>}
                    <Badge kind={q.generation_mode === 'ai' ? 'green' : 'neutral'}>
                      {q.generation_mode === 'ai' ? 'AI-generated · trainer reviewed' : 'rules-based fallback · trainer reviewed'}
                    </Badge>
                  </div>
                  <div style={{ fontSize: 12.8, color: 'var(--ink-400)', marginTop: 3 }}>
                    {q.question_count} questions · created by {q.created_by_name} · {String(q.created_at).slice(0, 10)}
                  </div>
                </div>
                <Link to={`/learner/quizzes/${q.id}`}><Button size="sm">{t('action.start')} →</Button></Link>
              </Card>
            ))}
          </div>
          )}
    </>
  )
}
